source 'https://github.com/CocoaPods/Specs.git'

target 'OCProjector', :exclusive => true do
  pod "OCProjector", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "OCProjector", :path => "../"

  pod 'Kiwi'
end
